name: 'Test Reporter'
on:
  push:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            junit.xml;
          test_file_prefix: -file://CD-TREN/D:/github/JavaTemplate/

            
permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write
